### ISSUE TITLE
ContactUs - Remove Address, Separate Support/Careers

### ISSUE THREAD

**Issue by ctrlplusus** [ctrlplusus/ctrlplusus.github.io#2]
On the Contact Us section there are three sections (Support/Career, Phone, Address).

Change that to ( Support, Phone, Career).  
- Create a new Google group to handle careers@ctrlplus.us
- Use the new google group for the careers portion.  Also ensure icon is for email.
- Remove Address completely.

**Comment by bradctrlplus** [comment]
@risey3k.  Looks like the changes were already made and last week I created and tested that careers@ctrlplus.us is working.  Closing issue.
